[package]
name = "yakuza_friday"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bsky-sdk = "0.1.9"
env_logger = "0.11"
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"